//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Field_Tbl
    {
        public int Field_ID { get; set; }
        public string Field_Name { get; set; }
        public string Field_Description { get; set; }
        public int TBL_ID { get; set; }
        public string ServerName { get; set; }
        public string DBName { get; set; }
        public string TableName { get; set; }
        public string SchemaName { get; set; }
        public string DataType { get; set; }
        public Nullable<int> Prec { get; set; }
        public Nullable<int> ColumnLength { get; set; }
        public string is_null { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual Table_Tbl Table_Tbl { get; set; }
    }
}
