//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Field_Tbl
    {
        public int Field_ID { get; set; }
        public string Field_Name { get; set; }
        public string Field_Description { get; set; }
        public int TBL_ID { get; set; }
        public int data_type { get; set; }
        public Nullable<int> ObjectTypeID { get; set; }
    
        public virtual Table_Tbl Table_Tbl { get; set; }
        public virtual lk_ObjectType lk_ObjectType { get; set; }
    }
}
